name: Surge deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to darkdragon276.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ surge.SURGE_DOMAIN }}
          project: '.'
          login: ${{ surge.SURGE_EMAIL }}
          token: ${{ surge.SURGE_TOKEN }}